/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Avadhut Chintan Devstan Trust API
 * OpenAPI spec version: 0.1.0
 */
export interface Event {
    id: number;
    title: string;
    titleMr: string;
    description: string;
    descriptionMr: string;
    eventDate: string;
    location: string;
    locationMr: string;
    /** @nullable */
    imageUrl?: string | null;
    createdAt: string;
}
//# sourceMappingURL=event.d.ts.map