/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Avadhut Chintan Devstan Trust API
 * OpenAPI spec version: 0.1.0
 */
import type { OrderItem } from "./orderItem";
export interface Order {
    id: number;
    orderNumber: string;
    customerName: string;
    customerPhone: string;
    customerEmail: string;
    deliveryAddress: string;
    pincode: string;
    city: string;
    state: string;
    items: OrderItem[];
    totalAmount: number;
    paymentMethod: string;
    paymentStatus: string;
    orderStatus: string;
    /** @nullable */
    razorpayOrderId?: string | null;
    /** @nullable */
    razorpayPaymentId?: string | null;
    createdAt: string;
}
//# sourceMappingURL=order.d.ts.map