/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Avadhut Chintan Devstan Trust API
 * OpenAPI spec version: 0.1.0
 */
export interface ProductInput {
    name: string;
    nameMr: string;
    price: number;
    description: string;
    descriptionMr: string;
    /** @nullable */
    imageUrl?: string | null;
    inStock?: boolean;
}
//# sourceMappingURL=productInput.d.ts.map